

window.DEPARTMENTS = {
  cs: {
    name: 'Computer Science & Engineering',
    code: 'CSE',
    emoji: '💻',
    intake: 180,
    established: 1984,
    hod: 'Dr. Ravi Kumar S.',
    color: '#1a4b8c',
    about: `The Department of Computer Science & Engineering at BMSCE is one of the most sought-after departments, offering a rigorous curriculum aligned with global industry standards. Founded in 1984, the department has produced thousands of successful engineers who lead the technology landscape.`,
    programs: ['B.E. Computer Science', 'M.Tech CSE', 'Ph.D Program'],
    vision: 'To be a globally recognized department fostering innovation, research and excellence in computer science education.',
    facilities: ['Advanced Computing Lab', 'AI/ML Lab', 'Cybersecurity Lab', 'Cloud Computing Lab', 'Software Engineering Lab'],
    faculty: [
      { name: 'Dr. Ravi Kumar S.', designation: 'Professor & HOD', expertise: 'Machine Learning' },
      { name: 'Dr. Shobha G.', designation: 'Professor', expertise: 'Data Mining' },
      { name: 'Dr. Anitha M.', designation: 'Assoc. Professor', expertise: 'Computer Networks' },
      { name: 'Dr. Nagesh H.R.', designation: 'Professor', expertise: 'Cloud Computing' },
      { name: 'Ms. Divya B.S.', designation: 'Asst. Professor', expertise: 'Web Technologies' },
      { name: 'Mr. Kiran P.', designation: 'Asst. Professor', expertise: 'Algorithms' },
    ],
    placements: { rate: 98, avg: '₹14.2 LPA', highest: '₹62 LPA', companies: ['Google', 'Microsoft', 'Amazon', 'Infosys', 'TCS', 'Wipro'] },
    alumni: 4200,
    desc: 'Pioneering excellence in computing since 1984.',
  },
  ece: {
    name: 'Electronics & Communication Engineering',
    code: 'ECE',
    emoji: '📡',
    intake: 120,
    established: 1967,
    hod: 'Dr. Uma B.V.',
    color: '#0d2b55',
    about: `Electronics & Communication Engineering at BMSCE is one of the oldest and most prestigious departments. The department offers cutting-edge infrastructure in VLSI design, embedded systems, and communication systems.`,
    programs: ['B.E. Electronics & Comm.', 'M.Tech VLSI', 'Ph.D Program'],
    vision: 'To nurture globally competent engineers in electronics and communication with strong ethical values.',
    facilities: ['VLSI Design Lab', 'Embedded Systems Lab', 'Communication Lab', 'Signal Processing Lab', 'IoT Lab'],
    faculty: [
      { name: 'Dr. Uma B.V.', designation: 'Professor & HOD', expertise: 'VLSI Design' },
      { name: 'Dr. Suresh P.', designation: 'Professor', expertise: 'Signal Processing' },
      { name: 'Dr. Kavitha K.', designation: 'Assoc. Professor', expertise: 'Embedded Systems' },
      { name: 'Mr. Arun R.', designation: 'Asst. Professor', expertise: 'IoT' },
    ],
    placements: { rate: 94, avg: '₹11.8 LPA', highest: '₹45 LPA', companies: ['Intel', 'Qualcomm', 'Samsung', 'Texas Instruments', 'L&T', 'ISRO'] },
    alumni: 3800,
    desc: 'Connecting the world through electronics excellence.',
  },
  mech: {
    name: 'Mechanical Engineering',
    code: 'ME',
    emoji: '⚙️',
    intake: 120,
    established: 1946,
    hod: 'Dr. Basavarajappa N.S.',
    color: '#1a3a68',
    about: `Mechanical Engineering is the founding department of BMSCE, established in 1946. It offers world-class education in thermal engineering, manufacturing, design, and mechatronics with state-of-the-art laboratories.`,
    programs: ['B.E. Mechanical Engineering', 'M.Tech Machine Design', 'M.Tech Thermal Power', 'Ph.D Program'],
    vision: 'To produce mechanical engineers of highest calibre contributing to technology and society.',
    facilities: ['CNC Lab', 'CAD/CAM Lab', 'Heat Transfer Lab', 'Fluid Mechanics Lab', '3D Printing Lab'],
    faculty: [
      { name: 'Dr. Basavarajappa N.S.', designation: 'Professor & HOD', expertise: 'Tribology' },
      { name: 'Dr. Manjunath K.', designation: 'Professor', expertise: 'Thermal Engineering' },
      { name: 'Dr. Prasad K.', designation: 'Assoc. Professor', expertise: 'Machine Design' },
      { name: 'Ms. Rekha T.', designation: 'Asst. Professor', expertise: 'Manufacturing' },
    ],
    placements: { rate: 90, avg: '₹9.5 LPA', highest: '₹38 LPA', companies: ['L&T', 'BHEL', 'DRDO', 'Boeing', 'HAL', 'Caterpillar'] },
    alumni: 5100,
    desc: 'Engineering the future with precision and innovation.',
  },
  civil: {
    name: 'Civil Engineering',
    code: 'CE',
    emoji: '🏗️',
    intake: 60,
    established: 1958,
    hod: 'Dr. Chandrashekar P.',
    color: '#0a1628',
    about: `The Civil Engineering department at BMSCE prepares students to design, build and maintain the infrastructure of tomorrow. With strong industry connections and research facilities, graduates contribute to landmark projects across India and the world.`,
    programs: ['B.E. Civil Engineering', 'M.Tech Structural Engineering', 'M.Tech Environmental Engineering', 'Ph.D Program'],
    vision: 'To build a sustainable world through excellence in civil engineering education and research.',
    facilities: ['Concrete & Materials Lab', 'Geotechnical Lab', 'Hydraulics Lab', 'Survey Lab', 'GIS & Remote Sensing Lab'],
    faculty: [
      { name: 'Dr. Chandrashekar P.', designation: 'Professor & HOD', expertise: 'Structural Engineering' },
      { name: 'Dr. Sudheer K.', designation: 'Professor', expertise: 'Geotechnics' },
      { name: 'Ms. Anitha R.', designation: 'Asst. Professor', expertise: 'Environmental Eng.' },
    ],
    placements: { rate: 85, avg: '₹8.2 LPA', highest: '₹28 LPA', companies: ['L&T Construction', 'NHAI', 'PWD', 'Shapoorji Pallonji', 'Afcons'] },
    alumni: 2800,
    desc: 'Building the infrastructure of a better tomorrow.',
  },
  aiml: {
    name: 'Artificial Intelligence & Machine Learning',
    code: 'AIML',
    emoji: '🤖',
    intake: 60,
    established: 2019,
    hod: 'Dr. Prakash N.',
    color: '#2d1060',
    about: `The AIML department is one of BMSCE's newest and most dynamic departments, established to address the rapidly growing demand for AI expertise. It offers cutting-edge curriculum in deep learning, NLP, computer vision, and AI ethics.`,
    programs: ['B.E. AI & Machine Learning', 'M.Tech AI', 'Research Programs'],
    vision: 'To be at the forefront of AI research and education, creating responsible AI practitioners.',
    facilities: ['GPU Computing Lab', 'NLP Research Lab', 'Computer Vision Lab', 'Robotics Lab', 'Data Science Studio'],
    faculty: [
      { name: 'Dr. Prakash N.', designation: 'Professor & HOD', expertise: 'Deep Learning' },
      { name: 'Dr. Smitha K.', designation: 'Assoc. Professor', expertise: 'NLP' },
      { name: 'Mr. Vivek M.', designation: 'Asst. Professor', expertise: 'Computer Vision' },
      { name: 'Ms. Priya L.', designation: 'Asst. Professor', expertise: 'Reinforcement Learning' },
    ],
    placements: { rate: 97, avg: '₹18.5 LPA', highest: '₹75 LPA', companies: ['Google DeepMind', 'OpenAI', 'Meta AI', 'Amazon Alexa', 'Microsoft Research'] },
    alumni: 180,
    desc: 'Shaping the intelligence of tomorrow.',
  },
  ds: {
    name: 'Data Science',
    code: 'DS',
    emoji: '📊',
    intake: 60,
    established: 2020,
    hod: 'Dr. Anusha R.',
    color: '#0a2818',
    about: `Data Science at BMSCE empowers students with skills to extract insights from massive datasets. The department bridges mathematics, programming, and domain expertise to solve real-world problems through data-driven decisions.`,
    programs: ['B.E. Data Science', 'M.Tech Data Analytics', 'Research Programs'],
    vision: 'To develop world-class data scientists who drive evidence-based innovation.',
    facilities: ['Big Data Lab', 'Statistics Studio', 'Visualization Lab', 'Cloud Data Lab', 'Business Intelligence Centre'],
    faculty: [
      { name: 'Dr. Anusha R.', designation: 'Professor & HOD', expertise: 'Big Data Analytics' },
      { name: 'Dr. Mohan K.', designation: 'Assoc. Professor', expertise: 'Statistical Learning' },
      { name: 'Ms. Kritika P.', designation: 'Asst. Professor', expertise: 'Data Visualization' },
    ],
    placements: { rate: 96, avg: '₹16.2 LPA', highest: '₹68 LPA', companies: ['Databricks', 'Snowflake', 'Google', 'JPMorgan', 'Goldman Sachs', 'Nielsen'] },
    alumni: 120,
    desc: 'Transforming data into decisions and discovery.',
  },
  eee: {
    name: 'Electrical & Electronics Engineering',
    code: 'EEE',
    emoji: '⚡',
    intake: 60,
    established: 1967,
    hod: 'Dr. Sheela A.',
    color: '#1a0a00',
    about: `The EEE department at BMSCE has a rich heritage of producing electrical engineers who power the nation's infrastructure. From power systems to renewable energy, the department offers comprehensive education in electrical technologies.`,
    programs: ['B.E. Electrical & Electronics', 'M.Tech Power Electronics', 'M.Tech Power Systems', 'Ph.D Program'],
    vision: 'To power the future through excellence in electrical engineering education and sustainable innovation.',
    facilities: ['Power Electronics Lab', 'High Voltage Lab', 'Renewable Energy Lab', 'Smart Grid Lab', 'Control Systems Lab'],
    faculty: [
      { name: 'Dr. Sheela A.', designation: 'Professor & HOD', expertise: 'Power Systems' },
      { name: 'Dr. Ramesh G.', designation: 'Professor', expertise: 'Power Electronics' },
      { name: 'Ms. Nalini S.', designation: 'Asst. Professor', expertise: 'Renewable Energy' },
    ],
    placements: { rate: 88, avg: '₹9.8 LPA', highest: '₹35 LPA', companies: ['ABB', 'Siemens', 'MSEDCL', 'BESCOM', 'Schneider Electric', 'NTPC'] },
    alumni: 2400,
    desc: 'Powering innovation through electrical excellence.',
  },
  biotech: {
    name: 'Biotechnology',
    code: 'BT',
    emoji: '🧬',
    intake: 60,
    established: 2001,
    hod: 'Dr. Latha K.R.',
    color: '#001a0a',
    about: `Biotechnology at BMSCE offers an exciting interdisciplinary program combining biology, chemistry, and engineering. Students develop expertise in genetic engineering, bioinformatics, pharmaceutical development, and environmental biotech.`,
    programs: ['B.E. Biotechnology', 'M.Tech Bioinformatics', 'Ph.D Program'],
    vision: 'To harness the power of life sciences to create solutions for global health and sustainability challenges.',
    facilities: ['Molecular Biology Lab', 'Tissue Culture Lab', 'Bioinformatics Lab', 'Fermentation Lab', 'Genomics Lab'],
    faculty: [
      { name: 'Dr. Latha K.R.', designation: 'Professor & HOD', expertise: 'Molecular Biology' },
      { name: 'Dr. Padma V.', designation: 'Professor', expertise: 'Bioinformatics' },
      { name: 'Ms. Sindhu N.', designation: 'Asst. Professor', expertise: 'Genetic Engineering' },
    ],
    placements: { rate: 82, avg: '₹8.5 LPA', highest: '₹30 LPA', companies: ['Biocon', 'Syngene', 'GSK', 'Dr. Reddy\'s', 'Novozymes', 'Serum Institute'] },
    alumni: 1200,
    desc: 'Engineering life for a healthier world.',
  },
};

window.EVENTS = [
  { id: 1, title: 'UTSAV 2026 – Annual Tech & Cultural Fest', date: 'March 15–17, 2025', type: 'Fest', emoji: '🎉', desc: 'Three days of technical events, cultural performances, competitions, and workshops featuring over 50 events.', venue: 'BMSCE Campus', registration: 'Open' },
  { id: 2, title: 'Smart India Hackathon – Campus Qualifier', date: 'February 8, 2025', type: 'Hackathon', emoji: '💡', desc: 'Campus-level qualifier for the prestigious Smart India Hackathon. Form teams of 6 and solve real-world problems.', venue: 'CS & ECE Department', registration: 'Open' },
  { id: 3, title: 'Alumni Connect 2025', date: 'January 25, 2025', type: 'Alumni', emoji: '🤝', desc: 'Annual alumni meet featuring panel discussions, networking sessions, and inspiring talks from industry leaders.', venue: 'Main Auditorium', registration: 'Closed' },
  { id: 4, title: 'National Conference on AI & Robotics', date: 'April 3–4, 2025', type: 'Conference', emoji: '🤖', desc: 'Two-day national conference featuring keynote speakers, research paper presentations and workshops on AI, ML, and Robotics.', venue: 'Seminar Hall', registration: 'Open' },
  { id: 5, title: 'Industry Immersion Week', date: 'March 1–5, 2025', type: 'Industry', emoji: '🏭', desc: 'Week-long industry exposure program with expert sessions, company visits, and live project walkthroughs.', venue: 'Various Venues', registration: 'Closed' },
  { id: 6, title: 'IEEE BMSCE Student Chapter – Workshop on IoT', date: 'April 20, 2025', type: 'Workshop', emoji: '📡', desc: 'Hands-on workshop on Internet of Things development using Raspberry Pi and Arduino platforms.', venue: 'ECE Department Lab', registration: 'Open' },
];

window.ALUMNI_DATA = [
  { name: 'Kiran Rao', dept: 'cs', batch: '2012', role: 'VP Engineering', company: 'Google', initial: 'K' },
  { name: 'Priya Menon', dept: 'ece', batch: '2010', role: 'Director, Hardware', company: 'Apple', initial: 'P' },
  { name: 'Suresh Kumar', dept: 'mech', batch: '2008', role: 'Chief Design Engineer', company: 'Boeing', initial: 'S' },
  { name: 'Ananya Singh', dept: 'cs', batch: '2015', role: 'Principal SWE', company: 'Microsoft', initial: 'A' },
  { name: 'Rahul Sharma', dept: 'eee', batch: '2011', role: 'CTO', company: 'Siemens India', initial: 'R' },
  { name: 'Divya Nair', dept: 'biotech', batch: '2013', role: 'Research Scientist', company: 'Biocon', initial: 'D' },
  { name: 'Vikram Patel', dept: 'civil', batch: '2009', role: 'Project Director', company: 'L&T Construction', initial: 'V' },
  { name: 'Meera Krishnan', dept: 'ece', batch: '2014', role: 'VLSI Engineer', company: 'Intel', initial: 'M' },
  { name: 'Aditya Reddy', dept: 'cs', batch: '2017', role: 'ML Engineer', company: 'Amazon', initial: 'A' },
  { name: 'Lakshmi S.', dept: 'ds', batch: '2022', role: 'Data Scientist', company: 'Goldman Sachs', initial: 'L' },
  { name: 'Rohan Gowda', dept: 'aiml', batch: '2023', role: 'AI Researcher', company: 'Google DeepMind', initial: 'R' },
  { name: 'Sneha Patil', dept: 'mech', batch: '2016', role: 'Design Lead', company: 'HAL', initial: 'S' },
];

window.SEARCH_DATA = [{ label: 'Computer Science Department', page: 'dept', param: 'cs', icon: '💻' },
  { label: 'Electronics & Communication', page: 'dept', param: 'ece', icon: '📡' },
  { label: 'Mechanical Engineering', page: 'dept', param: 'mech', icon: '⚙️' },
  { label: 'Civil Engineering', page: 'dept', param: 'civil', icon: '🏗️' },
  { label: 'AI & Machine Learning', page: 'dept', param: 'aiml', icon: '🤖' },
  { label: 'Data Science', page: 'dept', param: 'ds', icon: '📊' },
  { label: 'Electrical Engineering', page: 'dept', param: 'eee', icon: '⚡' },
  { label: 'Biotechnology', page: 'dept', param: 'biotech', icon: '🧬' },
  { label: 'Placements & Careers', page: 'placements', param: null, icon: '💼' },
  { label: 'Alumni Network', page: 'alumni', param: null, icon: '🤝' },
  { label: 'Events & Fest', page: 'events', param: null, icon: '🎉' },
  { label: 'Research', page: 'research', param: null, icon: '🔬' },
  { label: 'Campus Life', page: 'campus', param: null, icon: '🏛️' },
  { label: 'Admissions', page: 'admissions', param: null, icon: '📝' },
];

window.CHATBOT_RESPONSES = {
  admissions: 'Admissions for 2025–26 are open! We offer B.E., M.Tech, and Ph.D programs. Entry is through KCET, PGCET, or Management Quota. Click "Admissions" in the nav for details.',
  placement: 'BMSCE has a 98% placement rate! Average package is ₹12.5 LPA, highest ₹75 LPA. Top recruiters include Google, Microsoft, Amazon, and 250+ other companies.',
  placements: 'BMSCE has a 98% placement rate! Average package is ₹12.5 LPA, highest ₹75 LPA. Top recruiters include Google, Microsoft, Amazon, and 250+ other companies.',
  fee: 'B.E. fees range from ~₹80,000/yr (Govt. quota) to ~₹2.5L/yr (Management quota). M.Tech is ~₹1.2L/yr. Contact the admissions office for the latest figures.',
  hostel: 'BMSCE has separate hostels for boys and girls with modern amenities, Wi-Fi, mess, and 24×7 security. Contact the hostel office for availability.',
  campus: 'Our 20-acre campus in Basavanagudi, Bangalore has a central library, sports complex, cafeteria, health centre, and world-class labs.',
  department: 'We have 8 departments: CSE, ECE, Mechanical, Civil, AI&ML, Data Science, EEE, and Biotechnology. Ask me about any specific one!',
  cs: 'The CSE department was established in 1984 with 180 seats. It has a 98% placement rate and avg package of ₹14.2 LPA. Click on the CS department to learn more.',
  ece: 'ECE was established in 1967 with 120 seats. Great for VLSI, embedded systems, and communication careers. Avg package: ₹11.8 LPA.',
  aiml: 'AIML is our newest and hottest department! Established in 2019, it has a 97% placement rate and avg package of ₹18.5 LPA. Top placements at Google DeepMind and OpenAI!',
  events: 'Check out UTSAV 2025, our annual tech & cultural fest (March 15–17). We also have hackathons, conferences, and workshops throughout the year!',
  alumni: 'BMSCE has 30,000+ alumni worldwide in top companies and leadership roles. Visit the Alumni page to connect and network.',
  default: "I'm here to help with BMSCE information! Ask about admissions, departments, placements, events, campus life, or alumni. You can also use the navigation bar to explore specific sections.",
};
